"""
This type stub file was generated by pyright.
"""

FILENAMES = ...
def get_file(file_alias: str) -> str:
    """Get the path of a local data file"""
    ...

def load_mapping(file_alias: str) -> dict:
    """Load an ISO 639 mapping JSON file"""
    ...

def load_langs() -> list:
    """Load the pickled list of ISO 639 Langs"""
    ...

