"""
This type stub file was generated by pyright.
"""

class InvalidLanguageValue(Exception):
    """Exception raised when the arguments and keyword arguments passed to
    the Lang constructor are not a valid combination of:
    - ISO 639 language name
    - ISO 639-1 language code
    - ISO 639-2B language code
    - ISO 639-2T language code
    - ISO 639-3 language code
    - ISO 639-5 language code
    """
    def __init__(self, *args, **kwargs) -> None:
        ...
    


class DeprecatedLanguageValue(Exception):
    """Exception raised when the arguments and keyword arguments passed to the
    Lang constructor point to a deprecated ISO 639-3 language code
    """
    def __init__(self, *args, **kwargs) -> None:
        ...
    


