repos:
  - repo: https://github.com/hhatto/autopep8
    rev: 'v2.1.0'
    hooks:
      - id: autopep8
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.3.3'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
