repos:
    - repo: https://github.com/pre-commit/mirrors-autopep8
      rev: "v2.0.2"
      hooks:
          - id: autopep8
    - repo: https://github.com/charliermarsh/ruff-pre-commit
      # Ruff version.
      rev: 'v0.0.267'
      hooks:
          - id: ruff
            args: [ --fix, --exit-non-zero-on-fix ]
